Fill topology and math statistics sections with new fragments
ShunkevichDV/ostisalgebra pull request #11
Opened 2021-12-17 11:14 UTC by fintarin

- Topology: new 10 sections, 13 concepts

2021-12-17 11:25 UTC, ShunkevichDV requested changes

2021-12-17 11:25 UTC, ShunkevichDV commented on kb/knowledge_base_of_numeric_models/sections/section_mathematical_statistics/rels/nrel_correlation/corelation.scs
> +[correlation* ](*<-lang_en;;*);;
Не нужно оставлять пробелы в идентификаторах, везде нужно проверить

2021-12-17 11:25 UTC, ShunkevichDV commented on kb/knowledge_base_of_numeric_models/sections/section_topology/sections/section_algebraic_topology/concepts/concept_topological_space/topological_space.scs
> +      [Топологическое пространство - это набор точек вместе с набором окрестностей для каждой точки, удовлетворяющий набору аксиом, связывающих точки и окрестности.](*<-lang_ru;;*);;
Крайне желательно поправить форматирование здесь и в других местах

2021-12-17 11:25 UTC, ShunkevichDV commented on kb/knowledge_base_of_numeric_models/sections/section_topology/sections/section_algebraic_topology/sections/section_homology/section_subject_domain_of_homology.scs
> +        [Предметная область гомология] (* <- lang_ru;; *);
гомологиЙ видимо

2021-12-17 11:25 UTC, ShunkevichDV commented on kb/knowledge_base_of_numeric_models/sections/section_topology/sections/section_algebraic_topology/sections/section_homotopy_groups/section_subject_domain_of_homotopy_groups.scs
> +    [Раздел. Предметная область гомотопическая группа] (* <- lang_ru;; *);
везде родительный падеж, "гомотопических групп"

2021-12-19 21:23 UTC, fintarin commented on kb/knowledge_base_of_numeric_models/sections/section_mathematical_statistics/rels/nrel_correlation/corelation.scs
> +[correlation* ](*<-lang_en;;*);;
Fixed in current files. To be fixed in all files in the future

2021-12-19 21:24 UTC, fintarin commented on kb/knowledge_base_of_numeric_models/sections/section_topology/sections/section_algebraic_topology/concepts/concept_topological_space/topological_space.scs
> +      [Топологическое пространство - это набор точек вместе с набором окрестностей для каждой точки, удовлетворяющий набору аксиом, связывающих точки и окрестности.](*<-lang_ru;;*);;
Fixed in some places, because we don't have codestyle yet

2021-12-19 21:24 UTC, fintarin commented on kb/knowledge_base_of_numeric_models/sections/section_topology/sections/section_algebraic_topology/sections/section_homology/section_subject_domain_of_homology.scs
> +        [Предметная область гомология] (* <- lang_ru;; *);
Fixed

2021-12-19 21:24 UTC, fintarin commented on kb/knowledge_base_of_numeric_models/sections/section_topology/sections/section_algebraic_topology/sections/section_homotopy_groups/section_subject_domain_of_homotopy_groups.scs
> +    [Раздел. Предметная область гомотопическая группа] (* <- lang_ru;; *);
Fixed

2022-01-25 10:27 UTC, ShunkevichDV approved these changes

2022-01-25 10:42 UTC, merged